### ISSUE TITLE
Authentication key leak

### ISSUE THREAD

**Issue by yasoob** [jblanfrey/Nike-Run-Club-Analysis#1]
Hi! I was going through your repo and saw that you had [hardcoded your authentication key](https://github.com/jblanfrey/Nike-Run-Club-Analysis/blob/master/saveData.m#L9) for NRC. Just wanted to make sure you were aware of that just in case it was accidental. :)

**Comment by yasoob** [comment]
And to answer your question whether it can be grabbed automatically or not, Nike uses Akamai bot detection which is slightly tricky to fool. I am also trying to work on a similar NRC data extraction related project. If trying to circumvent bot detection really excites you then it might be worth it to look at the following repos:

https://github.com/FlySolutions/Py-Abck-Lib
https://github.com/zedd3v/abck

**Comment by jblanfrey** [comment]
Hi yasoob,
thanks for the heads up.
the reason I left it here is that it changes all the time, so it is already invalid...
I'll have a look at the suggested repos.
JB

**Comment by yasoob** [comment]
Yeah I figured that might be the case. Do you mind sharing some details about what you are trying to do with this project? :)

**Comment by jblanfrey** [comment]
Get access to the run I log using the Nike app. Look at stats, see if I improve or not ;).
I'm also planning to export data to gpx format so I can upload my best runs to Strava which some of my friends use.

**Comment by yasoob** [comment]
Sweet! I did some super simple but fairly similar stuff a year ago as well: https://yasoob.me/posts/nike-run-club-data-visualization/ My interest got rekindled when I started reverse-engineering Android apps a couple of weeks ago. For now the aim is to figure out how I can defeat the bot detection. And the next aim is to do what you are planning on doing, convert the runs into gpx and upload them to Strava (and allow other people to do it as well using the same code-base).

Well, best of luck! I will be keeping tabs on your project :)

**Comment by jblanfrey** [comment]
I actually got inspired and found the solution from your post.
I already sorted out the visualisation part.
The export to gpx should be quite straightforward.

**Comment by yasoob** [comment]
Do you mind posting some pictures of the kinds of visualizations you are doing? I love seeing viz stuff. And have you done any research on the export to gpx functionality so far?

**Comment by jblanfrey** [comment]
Hi,
I added a picture.
little research on exporting to gpx yet.
maybe next week.

**Comment by yasoob** [comment]
Oh I like that! And yeah looking at a [sample gpx file](https://www.wikiwand.com/en/GPS_Exchange_Format), I don't think it will be particularly hard to convert the data.

**Comment by yasoob** [comment]
Spent some time this weekend and put together this [short script](https://github.com/yasoob/nrc-exporter) for downloading and converting data from Nike to GPX. The one issue is the elevation data. Nike provides us with the ascent and descent data for some runs. Right now I am only making use of ascent data (there are quite a few runs with only ascent data). Need to figure out how to make use of descent data as well.

Feel free to take a look and offer comments/suggestions.
